export interface StateData {
  id: string;
  name: string;
  abbreviation: string;
  capital: string;
  population: number;
  area: number;
  region: 'Northeast' | 'Southeast' | 'Midwest' | 'Southwest' | 'West';
  coordinates: { lat: number; lng: number };
  activeContractors: number;
  totalJobs: number;
  averageRating: number;
  topServices: string[];
  licensingAuthority: string;
  licensingWebsite: string;
}

export const US_STATES: StateData[] = [
  {
    id: 'AL',
    name: 'Alabama',
    abbreviation: 'AL',
    capital: 'Montgomery',
    population: 5024279,
    area: 52420,
    region: 'Southeast',
    coordinates: { lat: 32.806671, lng: -86.79113 },
    activeContractors: 245,
    totalJobs: 1823,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Alabama Licensing Board for General Contractors',
    licensingWebsite: 'https://gbcal.alabama.gov/'
  },
  {
    id: 'AK',
    name: 'Alaska',
    abbreviation: 'AK',
    capital: 'Juneau',
    population: 733391,
    area: 665384,
    region: 'West',
    coordinates: { lat: 61.370716, lng: -152.404419 },
    activeContractors: 89,
    totalJobs: 432,
    averageRating: 4.8,
    topServices: ['Heating', 'Insulation', 'Roofing'],
    licensingAuthority: 'Alaska Department of Commerce',
    licensingWebsite: 'https://commerce.alaska.gov/'
  },
  {
    id: 'AZ',
    name: 'Arizona',
    abbreviation: 'AZ',
    capital: 'Phoenix',
    population: 7151502,
    area: 113990,
    region: 'Southwest',
    coordinates: { lat: 33.729759, lng: -111.431221 },
    activeContractors: 892,
    totalJobs: 6234,
    averageRating: 4.7,
    topServices: ['HVAC', 'Pool Service', 'Landscaping'],
    licensingAuthority: 'Arizona Registrar of Contractors',
    licensingWebsite: 'https://roc.az.gov/'
  },
  {
    id: 'AR',
    name: 'Arkansas',
    abbreviation: 'AR',
    capital: 'Little Rock',
    population: 3011524,
    area: 53179,
    region: 'Southeast',
    coordinates: { lat: 34.969704, lng: -92.373123 },
    activeContractors: 178,
    totalJobs: 1245,
    averageRating: 4.5,
    topServices: ['Roofing', 'Electrical', 'Plumbing'],
    licensingAuthority: 'Arkansas Contractors Licensing Board',
    licensingWebsite: 'https://www.clb.arkansas.gov/'
  },
  {
    id: 'CA',
    name: 'California',
    abbreviation: 'CA',
    capital: 'Sacramento',
    population: 39538223,
    area: 163695,
    region: 'West',
    coordinates: { lat: 36.116203, lng: -119.681564 },
    activeContractors: 3542,
    totalJobs: 28934,
    averageRating: 4.6,
    topServices: ['Solar Installation', 'Earthquake Retrofitting', 'Pool Service'],
    licensingAuthority: 'California Contractors State License Board',
    licensingWebsite: 'https://www.cslb.ca.gov/'
  },
  {
    id: 'CO',
    name: 'Colorado',
    abbreviation: 'CO',
    capital: 'Denver',
    population: 5773714,
    area: 104094,
    region: 'West',
    coordinates: { lat: 39.059811, lng: -105.311104 },
    activeContractors: 654,
    totalJobs: 4823,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Colorado Department of Regulatory Agencies',
    licensingWebsite: 'https://dora.colorado.gov/'
  },
  {
    id: 'CT',
    name: 'Connecticut',
    abbreviation: 'CT',
    capital: 'Hartford',
    population: 3605944,
    area: 5543,
    region: 'Northeast',
    coordinates: { lat: 41.597782, lng: -72.755371 },
    activeContractors: 423,
    totalJobs: 3124,
    averageRating: 4.8,
    topServices: ['Heating', 'Snow Removal', 'Roofing'],
    licensingAuthority: 'Connecticut Department of Consumer Protection',
    licensingWebsite: 'https://portal.ct.gov/DCP'
  },
  {
    id: 'DE',
    name: 'Delaware',
    abbreviation: 'DE',
    capital: 'Dover',
    population: 989948,
    area: 2489,
    region: 'Northeast',
    coordinates: { lat: 39.318523, lng: -75.507141 },
    activeContractors: 98,
    totalJobs: 723,
    averageRating: 4.6,
    topServices: ['Roofing', 'Plumbing', 'Electrical'],
    licensingAuthority: 'Delaware Division of Professional Regulation',
    licensingWebsite: 'https://dpr.delaware.gov/'
  },
  {
    id: 'FL',
    name: 'Florida',
    abbreviation: 'FL',
    capital: 'Tallahassee',
    population: 21538187,
    area: 65758,
    region: 'Southeast',
    coordinates: { lat: 27.766279, lng: -81.686783 },
    activeContractors: 2834,
    totalJobs: 19234,
    averageRating: 4.5,
    topServices: ['Hurricane Prep', 'Pool Service', 'HVAC'],
    licensingAuthority: 'Florida Department of Business and Professional Regulation',
    licensingWebsite: 'https://www.myfloridalicense.com/'
  },
  {
    id: 'GA',
    name: 'Georgia',
    abbreviation: 'GA',
    capital: 'Atlanta',
    population: 10711908,
    area: 59425,
    region: 'Southeast',
    coordinates: { lat: 33.040619, lng: -83.643074 },
    activeContractors: 1234,
    totalJobs: 8923,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Landscaping'],
    licensingAuthority: 'Georgia Secretary of State',
    licensingWebsite: 'https://sos.ga.gov/'
  },
  {
    id: 'HI',
    name: 'Hawaii',
    abbreviation: 'HI',
    capital: 'Honolulu',
    population: 1455271,
    area: 10932,
    region: 'West',
    coordinates: { lat: 21.094318, lng: -157.498337 },
    activeContractors: 167,
    totalJobs: 1234,
    averageRating: 4.7,
    topServices: ['Roofing', 'Pool Service', 'Landscaping'],
    licensingAuthority: 'Hawaii Contractors License Board',
    licensingWebsite: 'https://cca.hawaii.gov/'
  },
  {
    id: 'ID',
    name: 'Idaho',
    abbreviation: 'ID',
    capital: 'Boise',
    population: 1839106,
    area: 83569,
    region: 'West',
    coordinates: { lat: 44.240459, lng: -114.478828 },
    activeContractors: 234,
    totalJobs: 1567,
    averageRating: 4.8,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Idaho Contractors Board',
    licensingWebsite: 'https://ibol.idaho.gov/'
  },
  {
    id: 'IL',
    name: 'Illinois',
    abbreviation: 'IL',
    capital: 'Springfield',
    population: 12812508,
    area: 57914,
    region: 'Midwest',
    coordinates: { lat: 40.349457, lng: -88.986137 },
    activeContractors: 1456,
    totalJobs: 10234,
    averageRating: 4.6,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Illinois Department of Financial and Professional Regulation',
    licensingWebsite: 'https://idfpr.illinois.gov/'
  },
  {
    id: 'IN',
    name: 'Indiana',
    abbreviation: 'IN',
    capital: 'Indianapolis',
    population: 6785528,
    area: 36420,
    region: 'Midwest',
    coordinates: { lat: 39.849426, lng: -86.258278 },
    activeContractors: 678,
    totalJobs: 4823,
    averageRating: 4.7,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Indiana Professional Licensing Agency',
    licensingWebsite: 'https://www.in.gov/pla/'
  },
  {
    id: 'IA',
    name: 'Iowa',
    abbreviation: 'IA',
    capital: 'Des Moines',
    population: 3190369,
    area: 56273,
    region: 'Midwest',
    coordinates: { lat: 42.011539, lng: -93.210526 },
    activeContractors: 345,
    totalJobs: 2456,
    averageRating: 4.8,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Iowa Division of Labor',
    licensingWebsite: 'https://www.iowaworkforcedevelopment.gov/'
  },
  {
    id: 'KS',
    name: 'Kansas',
    abbreviation: 'KS',
    capital: 'Topeka',
    population: 2937880,
    area: 82278,
    region: 'Midwest',
    coordinates: { lat: 38.5266, lng: -96.726486 },
    activeContractors: 298,
    totalJobs: 2134,
    averageRating: 4.7,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Kansas Department of Labor',
    licensingWebsite: 'https://www.dol.ks.gov/'
  },
  {
    id: 'KY',
    name: 'Kentucky',
    abbreviation: 'KY',
    capital: 'Frankfort',
    population: 4505836,
    area: 40408,
    region: 'Southeast',
    coordinates: { lat: 37.66814, lng: -84.670067 },
    activeContractors: 445,
    totalJobs: 3234,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Kentucky Department of Housing',
    licensingWebsite: 'https://dhbc.ky.gov/'
  },
  {
    id: 'LA',
    name: 'Louisiana',
    abbreviation: 'LA',
    capital: 'Baton Rouge',
    population: 4657757,
    area: 52378,
    region: 'Southeast',
    coordinates: { lat: 31.169546, lng: -91.867805 },
    activeContractors: 523,
    totalJobs: 3892,
    averageRating: 4.5,
    topServices: ['Hurricane Prep', 'Roofing', 'HVAC'],
    licensingAuthority: 'Louisiana State Licensing Board for Contractors',
    licensingWebsite: 'https://lslbc.louisiana.gov/'
  },
  {
    id: 'ME',
    name: 'Maine',
    abbreviation: 'ME',
    capital: 'Augusta',
    population: 1362359,
    area: 35380,
    region: 'Northeast',
    coordinates: { lat: 44.693947, lng: -69.381927 },
    activeContractors: 156,
    totalJobs: 1123,
    averageRating: 4.8,
    topServices: ['Snow Removal', 'Roofing', 'Heating'],
    licensingAuthority: 'Maine Department of Professional and Financial Regulation',
    licensingWebsite: 'https://www.maine.gov/pfr/'
  },
  {
    id: 'MD',
    name: 'Maryland',
    abbreviation: 'MD',
    capital: 'Annapolis',
    population: 6177224,
    area: 12406,
    region: 'Northeast',
    coordinates: { lat: 39.063946, lng: -76.802101 },
    activeContractors: 734,
    totalJobs: 5234,
    averageRating: 4.7,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Maryland Home Improvement Commission',
    licensingWebsite: 'https://www.dllr.state.md.us/license/mhic/'
  },
  {
    id: 'MA',
    name: 'Massachusetts',
    abbreviation: 'MA',
    capital: 'Boston',
    population: 7029917,
    area: 10554,
    region: 'Northeast',
    coordinates: { lat: 42.230171, lng: -71.530106 },
    activeContractors: 823,
    totalJobs: 6234,
    averageRating: 4.8,
    topServices: ['Snow Removal', 'Heating', 'Roofing'],
    licensingAuthority: 'Massachusetts Division of Professional Licensure',
    licensingWebsite: 'https://www.mass.gov/orgs/division-of-professional-licensure'
  },
  {
    id: 'MI',
    name: 'Michigan',
    abbreviation: 'MI',
    capital: 'Lansing',
    population: 10077331,
    area: 96714,
    region: 'Midwest',
    coordinates: { lat: 43.326618, lng: -84.536095 },
    activeContractors: 1123,
    totalJobs: 7823,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Michigan Department of Licensing and Regulatory Affairs',
    licensingWebsite: 'https://www.michigan.gov/lara'
  },
  {
    id: 'MN',
    name: 'Minnesota',
    abbreviation: 'MN',
    capital: 'Saint Paul',
    population: 5706494,
    area: 86936,
    region: 'Midwest',
    coordinates: { lat: 45.694454, lng: -93.900192 },
    activeContractors: 678,
    totalJobs: 4923,
    averageRating: 4.8,
    topServices: ['Snow Removal', 'Heating', 'Roofing'],
    licensingAuthority: 'Minnesota Department of Labor and Industry',
    licensingWebsite: 'https://www.dli.mn.gov/'
  },
  {
    id: 'MS',
    name: 'Mississippi',
    abbreviation: 'MS',
    capital: 'Jackson',
    population: 2961279,
    area: 48432,
    region: 'Southeast',
    coordinates: { lat: 32.741646, lng: -89.678696 },
    activeContractors: 234,
    totalJobs: 1723,
    averageRating: 4.5,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Mississippi State Board of Contractors',
    licensingWebsite: 'https://www.msboc.us/'
  },
  {
    id: 'MO',
    name: 'Missouri',
    abbreviation: 'MO',
    capital: 'Jefferson City',
    population: 6154913,
    area: 69707,
    region: 'Midwest',
    coordinates: { lat: 38.456085, lng: -92.288368 },
    activeContractors: 623,
    totalJobs: 4523,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Missouri Division of Professional Registration',
    licensingWebsite: 'https://pr.mo.gov/'
  },
  {
    id: 'MT',
    name: 'Montana',
    abbreviation: 'MT',
    capital: 'Helena',
    population: 1084225,
    area: 147040,
    region: 'West',
    coordinates: { lat: 46.921925, lng: -110.454353 },
    activeContractors: 134,
    totalJobs: 892,
    averageRating: 4.8,
    topServices: ['Roofing', 'Heating', 'Snow Removal'],
    licensingAuthority: 'Montana Department of Labor and Industry',
    licensingWebsite: 'https://dli.mt.gov/'
  },
  {
    id: 'NE',
    name: 'Nebraska',
    abbreviation: 'NE',
    capital: 'Lincoln',
    population: 1961504,
    area: 77348,
    region: 'Midwest',
    coordinates: { lat: 41.12537, lng: -98.268082 },
    activeContractors: 212,
    totalJobs: 1534,
    averageRating: 4.7,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Nebraska Department of Labor',
    licensingWebsite: 'https://dol.nebraska.gov/'
  },
  {
    id: 'NV',
    name: 'Nevada',
    abbreviation: 'NV',
    capital: 'Carson City',
    population: 3104614,
    area: 110572,
    region: 'West',
    coordinates: { lat: 38.313515, lng: -117.055374 },
    activeContractors: 456,
    totalJobs: 3234,
    averageRating: 4.6,
    topServices: ['HVAC', 'Pool Service', 'Landscaping'],
    licensingAuthority: 'Nevada State Contractors Board',
    licensingWebsite: 'https://www.nscb.nv.gov/'
  },
  {
    id: 'NH',
    name: 'New Hampshire',
    abbreviation: 'NH',
    capital: 'Concord',
    population: 1377529,
    area: 9349,
    region: 'Northeast',
    coordinates: { lat: 43.452492, lng: -71.563896 },
    activeContractors: 167,
    totalJobs: 1234,
    averageRating: 4.8,
    topServices: ['Snow Removal', 'Heating', 'Roofing'],
    licensingAuthority: 'New Hampshire Office of Professional Licensure',
    licensingWebsite: 'https://www.oplc.nh.gov/'
  },
  {
    id: 'NJ',
    name: 'New Jersey',
    abbreviation: 'NJ',
    capital: 'Trenton',
    population: 9288994,
    area: 8723,
    region: 'Northeast',
    coordinates: { lat: 40.298904, lng: -74.521011 },
    activeContractors: 1034,
    totalJobs: 7823,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'New Jersey Division of Consumer Affairs',
    licensingWebsite: 'https://www.njconsumeraffairs.gov/'
  },
  {
    id: 'NM',
    name: 'New Mexico',
    abbreviation: 'NM',
    capital: 'Santa Fe',
    population: 2117522,
    area: 121590,
    region: 'Southwest',
    coordinates: { lat: 34.840515, lng: -106.248482 },
    activeContractors: 267,
    totalJobs: 1823,
    averageRating: 4.6,
    topServices: ['HVAC', 'Roofing', 'Landscaping'],
    licensingAuthority: 'New Mexico Regulation and Licensing Department',
    licensingWebsite: 'https://www.rld.nm.gov/'
  },
  {
    id: 'NY',
    name: 'New York',
    abbreviation: 'NY',
    capital: 'Albany',
    population: 20201249,
    area: 54555,
    region: 'Northeast',
    coordinates: { lat: 42.165726, lng: -74.948051 },
    activeContractors: 2134,
    totalJobs: 15234,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'New York Department of State',
    licensingWebsite: 'https://www.dos.ny.gov/'
  },
  {
    id: 'NC',
    name: 'North Carolina',
    abbreviation: 'NC',
    capital: 'Raleigh',
    population: 10439388,
    area: 53819,
    region: 'Southeast',
    coordinates: { lat: 35.630066, lng: -79.806419 },
    activeContractors: 1234,
    totalJobs: 8723,
    averageRating: 4.7,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'North Carolina Licensing Board for General Contractors',
    licensingWebsite: 'https://www.nclbgc.org/'
  },
  {
    id: 'ND',
    name: 'North Dakota',
    abbreviation: 'ND',
    capital: 'Bismarck',
    population: 779094,
    area: 70698,
    region: 'Midwest',
    coordinates: { lat: 47.528912, lng: -99.784012 },
    activeContractors: 89,
    totalJobs: 623,
    averageRating: 4.8,
    topServices: ['Heating', 'Snow Removal', 'Roofing'],
    licensingAuthority: 'North Dakota Secretary of State',
    licensingWebsite: 'https://sos.nd.gov/'
  },
  {
    id: 'OH',
    name: 'Ohio',
    abbreviation: 'OH',
    capital: 'Columbus',
    population: 11799448,
    area: 44826,
    region: 'Midwest',
    coordinates: { lat: 40.388783, lng: -82.764915 },
    activeContractors: 1345,
    totalJobs: 9234,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Ohio Construction Industry Licensing Board',
    licensingWebsite: 'https://com.ohio.gov/divisions-and-programs/ocilb'
  },
  {
    id: 'OK',
    name: 'Oklahoma',
    abbreviation: 'OK',
    capital: 'Oklahoma City',
    population: 3959353,
    area: 69899,
    region: 'Southwest',
    coordinates: { lat: 35.565342, lng: -96.928917 },
    activeContractors: 423,
    totalJobs: 2934,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Oklahoma Construction Industries Board',
    licensingWebsite: 'https://www.ok.gov/cib/'
  },
  {
    id: 'OR',
    name: 'Oregon',
    abbreviation: 'OR',
    capital: 'Salem',
    population: 4237256,
    area: 98379,
    region: 'West',
    coordinates: { lat: 44.572021, lng: -122.070938 },
    activeContractors: 534,
    totalJobs: 3823,
    averageRating: 4.8,
    topServices: ['Roofing', 'Landscaping', 'HVAC'],
    licensingAuthority: 'Oregon Construction Contractors Board',
    licensingWebsite: 'https://www.oregon.gov/ccb/'
  },
  {
    id: 'PA',
    name: 'Pennsylvania',
    abbreviation: 'PA',
    capital: 'Harrisburg',
    population: 13002700,
    area: 46054,
    region: 'Northeast',
    coordinates: { lat: 40.590752, lng: -77.209755 },
    activeContractors: 1523,
    totalJobs: 10823,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Pennsylvania Department of Labor & Industry',
    licensingWebsite: 'https://www.dli.pa.gov/'
  },
  {
    id: 'RI',
    name: 'Rhode Island',
    abbreviation: 'RI',
    capital: 'Providence',
    population: 1097379,
    area: 1545,
    region: 'Northeast',
    coordinates: { lat: 41.680893, lng: -71.51178 },
    activeContractors: 123,
    totalJobs: 892,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Rhode Island Contractors Registration and Licensing Board',
    licensingWebsite: 'https://crb.ri.gov/'
  },
  {
    id: 'SC',
    name: 'South Carolina',
    abbreviation: 'SC',
    capital: 'Columbia',
    population: 5118425,
    area: 32020,
    region: 'Southeast',
    coordinates: { lat: 33.856892, lng: -80.945007 },
    activeContractors: 623,
    totalJobs: 4523,
    averageRating: 4.6,
    topServices: ['Hurricane Prep', 'Roofing', 'HVAC'],
    licensingAuthority: 'South Carolina Department of Labor, Licensing and Regulation',
    licensingWebsite: 'https://llr.sc.gov/'
  },
  {
    id: 'SD',
    name: 'South Dakota',
    abbreviation: 'SD',
    capital: 'Pierre',
    population: 886667,
    area: 77116,
    region: 'Midwest',
    coordinates: { lat: 44.299782, lng: -99.438828 },
    activeContractors: 98,
    totalJobs: 678,
    averageRating: 4.8,
    topServices: ['Roofing', 'Heating', 'Snow Removal'],
    licensingAuthority: 'South Dakota Department of Labor',
    licensingWebsite: 'https://dlr.sd.gov/'
  },
  {
    id: 'TN',
    name: 'Tennessee',
    abbreviation: 'TN',
    capital: 'Nashville',
    population: 6910840,
    area: 42144,
    region: 'Southeast',
    coordinates: { lat: 35.747845, lng: -86.692345 },
    activeContractors: 823,
    totalJobs: 5923,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Tennessee Board for Licensing Contractors',
    licensingWebsite: 'https://www.tn.gov/commerce/regboards/contractors.html'
  },
  {
    id: 'TX',
    name: 'Texas',
    abbreviation: 'TX',
    capital: 'Austin',
    population: 29145505,
    area: 268596,
    region: 'Southwest',
    coordinates: { lat: 31.054487, lng: -97.563461 },
    activeContractors: 3234,
    totalJobs: 24523,
    averageRating: 4.7,
    topServices: ['HVAC', 'Roofing', 'Pool Service'],
    licensingAuthority: 'Texas Department of Licensing and Regulation',
    licensingWebsite: 'https://www.tdlr.texas.gov/'
  },
  {
    id: 'UT',
    name: 'Utah',
    abbreviation: 'UT',
    capital: 'Salt Lake City',
    population: 3271616,
    area: 84897,
    region: 'West',
    coordinates: { lat: 40.150032, lng: -111.862434 },
    activeContractors: 423,
    totalJobs: 3123,
    averageRating: 4.8,
    topServices: ['HVAC', 'Roofing', 'Landscaping'],
    licensingAuthority: 'Utah Division of Occupational and Professional Licensing',
    licensingWebsite: 'https://dopl.utah.gov/'
  },
  {
    id: 'VT',
    name: 'Vermont',
    abbreviation: 'VT',
    capital: 'Montpelier',
    population: 643077,
    area: 9616,
    region: 'Northeast',
    coordinates: { lat: 44.045876, lng: -72.710686 },
    activeContractors: 78,
    totalJobs: 534,
    averageRating: 4.8,
    topServices: ['Snow Removal', 'Heating', 'Roofing'],
    licensingAuthority: 'Vermont Secretary of State',
    licensingWebsite: 'https://sos.vermont.gov/'
  },
  {
    id: 'VA',
    name: 'Virginia',
    abbreviation: 'VA',
    capital: 'Richmond',
    population: 8631393,
    area: 42775,
    region: 'Southeast',
    coordinates: { lat: 37.769337, lng: -78.169968 },
    activeContractors: 1034,
    totalJobs: 7523,
    averageRating: 4.7,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'Virginia Department of Professional and Occupational Regulation',
    licensingWebsite: 'https://www.dpor.virginia.gov/'
  },
  {
    id: 'WA',
    name: 'Washington',
    abbreviation: 'WA',
    capital: 'Olympia',
    population: 7705281,
    area: 71298,
    region: 'West',
    coordinates: { lat: 47.400902, lng: -121.490494 },
    activeContractors: 923,
    totalJobs: 6723,
    averageRating: 4.8,
    topServices: ['Roofing', 'Landscaping', 'HVAC'],
    licensingAuthority: 'Washington Department of Labor & Industries',
    licensingWebsite: 'https://lni.wa.gov/'
  },
  {
    id: 'WV',
    name: 'West Virginia',
    abbreviation: 'WV',
    capital: 'Charleston',
    population: 1793716,
    area: 24230,
    region: 'Southeast',
    coordinates: { lat: 38.491226, lng: -80.954456 },
    activeContractors: 178,
    totalJobs: 1234,
    averageRating: 4.6,
    topServices: ['Roofing', 'HVAC', 'Plumbing'],
    licensingAuthority: 'West Virginia Division of Labor',
    licensingWebsite: 'https://labor.wv.gov/'
  },
  {
    id: 'WI',
    name: 'Wisconsin',
    abbreviation: 'WI',
    capital: 'Madison',
    population: 5893718,
    area: 65496,
    region: 'Midwest',
    coordinates: { lat: 44.268543, lng: -89.616508 },
    activeContractors: 734,
    totalJobs: 5234,
    averageRating: 4.7,
    topServices: ['Snow Removal', 'Roofing', 'HVAC'],
    licensingAuthority: 'Wisconsin Department of Safety and Professional Services',
    licensingWebsite: 'https://dsps.wi.gov/'
  },
  {
    id: 'WY',
    name: 'Wyoming',
    abbreviation: 'WY',
    capital: 'Cheyenne',
    population: 576851,
    area: 97813,
    region: 'West',
    coordinates: { lat: 42.755966, lng: -107.30249 },
    activeContractors: 67,
    totalJobs: 456,
    averageRating: 4.8,
    topServices: ['Roofing', 'Heating', 'Snow Removal'],
    licensingAuthority: 'Wyoming Secretary of State',
    licensingWebsite: 'https://sos.wyo.gov/'
  }
];

export const getStateByAbbreviation = (abbreviation: string): StateData | undefined => {
  return US_STATES.find(state => state.abbreviation === abbreviation);
};

export const getStatesByRegion = (region: string): StateData[] => {
  return US_STATES.filter(state => state.region === region);
};

export const REGIONS = ['Northeast', 'Southeast', 'Midwest', 'Southwest', 'West'] as const;
